### ISSUE TITLE
Replace module with 5 lines?

### ISSUE THREAD

**Issue by jhg03a** [kimor79/puppet-module-package#3]
How is this module different than just adding the following to your base linux profile?
 ```
# Pull in the yum package data via hiera
  $yum_packages = lookup('package::packages', Hash, {
    'strategy'          => 'deep',
    'merge_hash_arrays' => true
  },{})
  create_resources('package',$yum_packages)

**Comment by kimor79** [comment]
Because 3-years-ago-me had a different knowledge of 3-years-ago puppet? :)

But the `package::package` function could possibly be removed. However, it does do the `if defined(Package[...])` check though.

Having the wrapper class does allow for those who don't have a "base linux" module. E.g., in hiera/common.yaml you can do:
```
classes:
  ...
  - ::package

**Comment by jhg03a** [comment]
Fair enough, I didn't think about putting packages directly in the hiera classes list.
